service: VandiumServerlessDemo

provider:
  name: aws
  runtime: nodejs6.10

functions:
    hello:
        handler: handler.hello
        events:
            - http:
                path: users/create
                method: get
            - http:
                path: users/create
                method: post
